### ISSUE TITLE
Local values are not persisted in the REPL

### ISSUE THREAD

**Issue by gpanders** [bakpakin/Fennel#400] opened 2021-10-19 19:14 UTC
To reproduce:

```fennel
>> (local x 4)
nil
>> x
nil
```

It should show `4`. This works on 0.10.0 but not main. Bisected to 48b6d5ba772e50f424f82fa6eb6432b313d68d7d.

**Comment by technomancy** [comment] 2021-10-20 15:28
I think I see what's wrong here; we were reinitializing the repl locals table on every loop instead of just doing it at the beginning. Should be fixed on the latest now!

**Closed by technomancy** 2021-10-20 15:28 UTC

**Comment by technomancy** [comment] 2021-10-20 18:58
I'm running the same input here and I can't reproduce the problem.

Is it possible you have `LUA_PATH` or something set such that `require("fennel")` is finding the older version? Do you still get this with `fennel = dofile("fennel.lua")`?

**Comment by gpanders** [comment] 2021-10-20 19:24
> Is it possible you have `LUA_PATH` or something set such that `require("fennel")` is finding the older version? Do you still get this with `fennel = dofile("fennel.lua")`?

Confirmed that `LUA_PATH` is empty and I can reproduce with `dofile()`. I've tried with Lua 5.4, 5.3, 5.2, and 5.1 -- same result on all of them (just ruling that out).

I can also reproduce in the standard Fennel REPL now too:

```
greande@r450058 fennel % git log -1
commit 2192c90383663664d0de57004cdbc6975f9a282d (HEAD -> main, origin/main, origin/HEAD)
Author: Phil Hagelberg <phil@hagelb.org>
Date:   Wed Oct 20 09:27:54 2021

    Fix initialization of repl locals table during repl saving.
greande@r450058 fennel % git clean -dfx
Removing fennel
Removing fennel.lua
greande@r450058 fennel % echo $LUA_PATH

greande@r450058 fennel % make
echo "#!/usr/bin/env lua" > fennel
lua old/launcher.lua --no-compiler-sandbox --add-fennel-path src/?.fnl --no-metadata --require-as-include --compile src/launcher.fnl >> fennel
chmod 755 fennel
lua old/launcher.lua --no-compiler-sandbox --add-fennel-path src/?.fnl --no-metadata --require-as-include --compile src/fennel.fnl > fennel.lua
greande@r450058 fennel % ./fennel
Welcome to Fennel 1.0.0-dev on Lua 5.4!
Use ,help to see available commands.
Try installing readline via luarocks for a better repl experience.
>> (local x 4)
nil
>> x
nil
>>
```

**Comment by technomancy** [comment] 2021-10-20 19:49
Weird! Does `make test` pass for you?

**Comment by technomancy** [comment] 2021-10-20 20:18
Never mind; I see there was a typo introduced somehow after I tested it that I missed. Pushed a fix.
