### ISSUE TITLE
Possible Bug In Conditional Tutorial Code

### ISSUE THREAD

**Issue by jmwright** [bakpakin/Fennel#340] opened 2020-12-27 23:37 UTC
I'm new to Fennel and have just been playing around, so please forgive me if I'm not understanding something and this is just noise. However, I've run this code and it breaks in the way I'd expect it to. The tutorial covers if statements, and checks for evens and multiples of 10 in line 299. Hopefully this link works: https://github.com/bakpakin/Fennel/blob/main/tutorial.md#L299

Here's the code:
```
(let [x (math.random 64)]
  (if (= 0 (% x 2))
      "even"
      (= 0 (% x 10))
      "multiple of ten"
      "I dunno, something else"))
```
Won't the "even" branch always override the "multiple of ten" branch since it runs before ten and ten is even? It seems like the code will only work as expected this way.
```
(let [x (math.random 64)]
  (if (= 0 (% x 10))
      "multiple of ten"
      (= 0 (% x 2))
      "even"
      "I dunno, something else"))
```
Also, unless `math.randomseed` is called before calling `math.random` I would always get the same value for x.
```
(math.randomseed (os.time))
```

**Comment by technomancy** [comment] 2020-12-28 03:28
Haha, yes, that's a good point. Not a bug exactly but a misleading and pointless example. Thanks for catching that.

Fixed in 7fe9016.

**Closed** 2020-12-28 03:28 UTC
