### ISSUE TITLE
Allow some way of loading macros that doesn't go through io.* functions

### ISSUE THREAD

**Issue by m-r-hunt** [bakpakin/Fennel#93] opened 2018-09-29 16:06 UTC
I'm using Fennel inside love2d. Although the environment has the io module, it doesn't work very well and cannot be used with a packaged game (as io can't read from inside the love archive). For now I've hacked the compiler to use love.filesystem instead of io in my own fork, but this solution can't really be contributed back here. It would be good if there was some way of using macros that didn't need to go through io.

Either that, or I can think about maintaining a fork that replaces all usage of io with love.filesystem. But I'd rather not do that...

**Comment by m-r-hunt** [comment] 2018-09-29 16:08
To be clear, `require-macros` uses `searchModule()` and `dofile_fennel()` internally which use the io.* functions to open and read the macro files. As far as I can tell there's no other way to provide the data to fennel.

**Comment by m-r-hunt** [comment] 2018-09-29 16:12
If you're curious, my hacked version is here: https://github.com/m-r-hunt/Fennel/tree/hacked-for-love

Replacing io with love.filesystem is pretty straightforward, but not totally mechanical as the APIs have some different functions/semantics.

**Comment by technomancy** [comment] 2018-12-28 01:43
I had an idea for implementing this; basically `require-macros` should be split into two things; one of them being a compile-time require which loads a module, and then once it finds the module it delegates to `macros` which is a special form which just takes a table of names to macro functions which get `macroToSpecial` called on them.

I'll see if I can push this out soon; maybe you'll find it useful.

**Comment by technomancy** [comment] 2018-12-29 01:19
This should take care of what you're thinking of: https://lists.sr.ht/%7Etechnomancy/fennel/%3C20181228055804.16653-1-phil%40hagelb.org%3E

Thoughts?

**Comment by thatismatt** [comment] 2018-12-29 08:42
I've just had a play with this, all worked as I expected. I'd love to have this in.

One minor thing, are the `@`s missing in your example `plus` macro? i.e. it should actually be:
```
(macros {:plus (fn [x y] `(+ @x @y))})
```

**Comment by technomancy** [comment] 2018-12-31 04:36
Oops; haha, yes that's what was intended.

This is fixed now in a5d9a92.

**Closed by technomancy** 2018-12-31 04:36 UTC

**Comment by m-r-hunt** [comment] 2019-01-07 21:08
Didn't have a chance to look at this over Christmas, but yes it looks good to me.
