### ISSUE TITLE
broken shadowing with nested `let`/`do`

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#218] opened 2020-01-07 19:46 UTC
Thanks to @norcalli for pointing this out to me.

I think @technomancy and I got this pretty narrowed down for a fix already, but I wanted to get it filed for documentation purposes so we can get it into `0.3.2`.

## Repro

```clojure
(let [t (let [t {} k :a]
          (tset t k 123) t)
      k :b]
  (tset t k 321) t)
```
The above code should work fine with the shadowed `t`, but what we see in the output is:

```lua
local t = t
do
  local t = {}
  local k = "a"
  t[k] = 123
  t = t
end
local k = "b"
t[k] = 321
return t
```

## Fact-finding

Changing one of the bindings from `t` to `t2` unsurprisingly corrects this behavior. You get the same output if you change the `let`'s to `(do (local t {}) (local k :a) ..)` etc. However, using `do` with a destructured declaration works as expected:

```clojure
(do (local (t k) (values (do (local (t k) (values {} :a))
                             (tset t k 123)
                             t)
                         :b))
  (tset t k 321) t)
```
Just the outer destructure (the inner one isn't necessary for it to work) results in:
```lua
local t, k = t, k
local _0_
do
  local t, k = {}, "a"
  t[k] = 123
  _0_ = t
end
t, k = _0_, "b"
t[k] = 321
return t
```
This should narrow down which bit of the expression handling we need to stop from misbehaving.

**Comment by jaawerth** [comment] 2020-01-07 22:26
I've narrowed the issue down to [doImpl naively assigning to outerTarget](https://github.com/bakpakin/Fennel/blob/e0e8754c0d315773b9ca2506b05cfcc73f632f1c/fennel.lua#L1321-L1333). Fix is incoming, wherein it generates an intermediate target when `outerTarget` exists in `subScope.manglings`.

**Comment by bakpakin** [comment] 2020-01-08 06:12
I'm pretty sure this is fixed, as of bb4481b, all of the tests pass. The solution was to simply try to get rid of aliasing in the first place, although this may have implications for other code, as we may rely on this kind of aliasing somewhere, although I don't think we do. It also may make the `local x = x` idiom not needed, although I haven't removed that.

**Comment by jaawerth** [comment] 2020-01-08 16:15
Nice! I started on that just-don't-shadow approach after abandoning my first go at this issue, but it felt like a pretty deep change given how many tests started failing just doing it in `declareLocal` without modifying the signature. This looks is an elegant way make the change without breaking functionality.

To your point about the `local x = x` idiom, this approach also lets us make more assumptions about whether a scope can access a given upvalue in the generated code, which should keep the need to emit confusingly defensive Lua output from being necessary.

As for the other implications, we might want to brainstorm what other tests we could add to cover various edge cases before we close this and release 0.3.2.

**Comment by bakpakin** [comment] 2020-01-10 21:14
Related `(let [print #(print $)] (print 10))` goes into an infinite loop.

Generated lua:
```lua
local print = nil
local function _0_(_241)
  return print(_241)
end
print = _0_
return print(10)
```

The problem is that the original fix for shadowing (`local x = x`) doesn't help in the general case.

**Comment by bakpakin** [comment] 2020-01-10 21:26
I have a fix that can emit a compiler error if you try to do this, but I would rather make this possible to do

**Comment by technomancy** [comment] 2020-01-11 01:25
What if we made it a compiler error for 0.3.2 and came back to it later with a more thorough fix? It's a minor annoyance, but flagging it as an error makes it easy to work around instead of scratching your head wondering why you're getting weird behavior.

**Comment by jaawerth** [comment] 2020-01-11 19:15
Wasn't that already an infinite loop? It certainly seems to be `0.3.0`, in which it produces
```lua
local print = print
local function _0_(_241)
  return print(_241)
end
print = _0_
return print(10)
```

I'm not sure I even see that as a bug. If you want to shadow a global or an upvalue with a local, you should either alias it or in the global case refer to it via `_G`, no? With `do` and `local`, that behavior would be expected, and `let` is semantically equivalent to `(do (local x vx) (local y vy) ...)`, right? In my opinion, aliasing the global you want to shadow first makes the code easier to reason about, so for what it's worth, personally I'd prefer we either leave it as-is or make it a compiler error and leave it that way.

**Comment by technomancy** [comment] 2020-01-12 23:32
No, it's an edge case but it's definitely a bug. In a let block, the binding isn't established until after the right-hand side is evaluated, otherwise this would also be an infinite cycle: `(let [a 1 a (+ a 2)] a)`. A closure in the right hand side has to refer to the environment that's present before that name/value pair is compiled.

**Comment by jaawerth** [comment] 2020-01-13 01:00
Ah, that makes sense. Yeah I could see going either way on that front in 0.4.0, then, but the compiler error makes sense for now!

**Comment by jaawerth** [comment] 2020-01-14 22:02
@technomancy @bakpakin I see we've got tests in place for the recursive global referencing compile error - was there anything else we wanted to account for before closing this and releasing `0.3.2`?

As a quick check since I knew it had some tests, I ran fnlfmt's tests against the current master and had no issue. No issues with (manually testing) fennel-nvim either.

**Comment by technomancy** [comment] 2020-01-15 01:17
Oh cool; I didn't realize that the compiler error for this had already landed. Cool. I gave it a spin with Polywell/Bussard and it seems to be in good order. I will cut a release in the next day or two.

**Closed** 2020-01-15 01:17 UTC
Labels: bug
