### ISSUE TITLE
incorrect output on let binding

### ISSUE THREAD

**Issue by robinvd** [bakpakin/Fennel#35] opened 2018-03-11 23:48 UTC
this fennel file:
```
(let [x 1
      r nil
      l 3]
      (print ""))
```
generates:
```
do
  local x = 1
  local r = nil
  return print((""))
end
```
this does not generate a local l var, leaking any later assignments to the global namespace.

with some testing i noticed that all let assignments after a nil assignment are ignored. So in the above example x is emitted but l is not.

Changing the assigment to `r false` fixes the problem

**Comment by bakpakin** [comment] 2018-03-12 00:20
This is because Lua tables cannot track length with embedded nils. This is a problem whenever the square bracket syntax is used for a table literal. To work around this, I have pushed a fix that allows using let with normal round bracketed bindings.

```
(let (x 1
      r nil
      l 3)
      (print ""))
```

This should fix your problem.

**Comment by technomancy** [comment] 2018-03-12 04:47
> This is because Lua tables cannot track length with embedded nils. This is a problem whenever the square bracket syntax is used for a table literal.

There is another possible fix; using pairs to iterate over the binding form will allow us to detect gaps in it. It's a bad idea for long tables, but since let forms rarely go over a handful of items it should be feasible.

**Comment by technomancy** [comment] 2018-03-13 01:05
There's another alternative that might be even better: what if we removed the parser case for nil and just emitted `nil` as a self-evaluating symbol? That way the binding vector wouldn't have any gaps in it, just a `sym("nil")` entry. I tried this out and it doesn't break any tests.

There is one downside to this approach; it doesn't flag `(let [nil 1] nil)` as an error; it just mangles `nil` into `_nil`. But I think this is better because this is a much less likely mistake to make.

**Comment by bakpakin** [comment] 2018-03-13 01:16
Unfortunately this will probably break if the user has defined the symbol _nil. I think the better approach is defining the table length throughout the compiler as the maximum integer key of a table. While this is slower, it happens at compile time so speed is not a huge issue.

**Comment by technomancy** [comment] 2018-03-13 02:29
I think I have a pretty simple fix for the `_nil` problem which would allow us to get out of the business of keeping the `tbl.n` field. I think that field makes it a bit tricky to write macros and special forms, because it's easy to edit a table and forget to change its `.n` value, so it would be nice to be able to avoid it. As I see it, the root cause of the problem is that `nil` can't be stored in a table, and it's better to embrace this fact than try to work around it.

I'll put together a PR and we can discuss there.

**Closed** 2018-03-13 03:45 UTC
