### ISSUE TITLE
Issue when strings containing @ are simplified

### ISSUE THREAD

**Issue by alexaandru** [bakpakin/Fennel#451] opened 2023-05-27 08:00 UTC
First of all, apologies if this is not the right place for reporting bugs related to **fnlfmt**. I would appreciate if you pointed me to the right place if that's the case.

Now for the actual issue:

Given an `x.fnl` file containing:

```Fennel
{"@foo.bar" 42}
```

`fnlfmt x.fnl` produces `{:@foo.bar 42}` which then throws `x.fnl:1:2 Parse error: invalid character: @` error.
I use `Fennel 1.3.1-dev on PUC Lua 5.4` and `fnlfmt version 0.3.1-dev`.

**Comment by technomancy** [comment] 2023-05-27 17:28
No problem; this is fine, thanks. In fact, this is a bug in Fennel itself; you get the same problem putting that table into the Fennel repl outside antifennel. The root cause is probably in `src/fennel/view.fnl`.

**Comment by technomancy** [comment] 2023-06-18 22:20
This should be fixed in 8404556; thanks for reporting.

**Closed by technomancy** 2023-06-18 22:20 UTC

**Comment by alexaandru** [comment] 2023-06-19 09:33
Awesome & you're most welcome! Cheers! :-)
